version: '3'
services:
  nodejs:
    container_name: nodejs_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5001:5001
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:14
    container_name: local_pgdb
    restart: always
    ports:
      - '54321:5432'
    environment:
      POSTGRES_DB: solidarIta
      POSTGRES_USER: *****
      POSTGRES_PASSWORD: *****
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
